version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=changeme
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
