global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['172.17.0.1:8080']

  - job_name: 'django-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:8000']